---
- name: Install python3 on all nodes
  hosts: all
  tags: python3
  vars:
    ansible_python_interpreter: /usr/bin/python
  tasks:
    - name: Install python3 on all nodes
      include_tasks: tasks/install_python3.yml

- name: include collection
  import_playbook: confluent.platform.all
