---
all:
  vars:
    ansible_connection: ssh
    ansible_user: vagrant
    ansible_become: true
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    health_checks_enabled: true
    redhat_java_package_name: java-1.8.0-openjdk
    rbac_enabled: true
    ##
    ## LDAP Users
    ## Note: Below users must already exist in your LDAP environment.  See kafka_broker vars, for LDAP connection details.
    mds_super_user: superUser
    mds_super_user_password: superUser
    kafka_broker_ldap_user: superUser
    kafka_broker_ldap_password: superUser
    # schema_registry_ldap_user: <Your Schema Registry username in LDAP>
    # schema_registry_ldap_password <Your schema  registry user's LDAP password>
    kafka_connect_ldap_user: superUser
    kafka_connect_ldap_password: superUser
    # ksql_ldap_user: <Your KSQL username in LDAP>
    # ksql_ldap_password: <Your KSQL user's password in LDAP>
    # kafka_rest_ldap_user: <Your REST Proxy's username in LDAP>
    # kafka_rest_ldap_password: <Your REST Proxy's password in LDAP>
    control_center_ldap_user: superUser
    control_center_ldap_password: superUser
    kafka_broker_custom_listeners:
      broker:
        name: BROKER
        port: 9093
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: scram
      internal:
        name: INTERNAL
        port: 9091
      client:
        name: UNAUTHCLIENT
        port: 9092
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: none

zookeeper:
  hosts:
    192.168.57.70:
    192.168.57.71:
    192.168.57.72:

kafka_broker:
  vars:
    ldap_config: |
      ldap.java.naming.factory.initial=com.sun.jndi.ldap.LdapCtxFactory
      ldap.com.sun.jndi.ldap.read.timeout=3000
      ldap.java.naming.provider.url=ldap://192.168.57.72:1389
      ldap.java.naming.security.principal=cn=admin,dc=confluentdemo,dc=io
      ldap.java.naming.security.credentials=admin
      ldap.java.naming.security.authentication=simple
      ldap.group.search.base=ou=groups,dc=confluentdemo,dc=io
      ldap.group.name.attribute=cn
      ldap.group.member.attribute=memberUid
      ldap.group.object.class=posixGroup
      ldap.group.member.attribute.pattern=cn=(.*),ou=users,dc=confluentdemo,dc=io
      ldap.user.search.base=ou=users,dc=confluentdemo,dc=io
      ldap.user.name.attribute=uid
      ldap.user.object.class=inetOrgPerson
    kafka_broker_service_environment_overrides:
      KAFKA_HEAP_OPTS: "-Xms1g -Xmx1g -XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35 -XX:G1HeapRegionSize=16M -XX:MinMetaspaceFreeRatio=50 -XX:MaxMetaspaceFreeRatio=80"
  hosts:
    192.168.57.70:
    192.168.57.71:
    192.168.57.72:

control_center:
  hosts:
    192.168.57.73:

#ksql:
#  hosts:
#    192.168.57.73: